# get all users
# GET http://localhost:3001/getUsers 

# create new user

POST http://localhost:3000/users
content-type: application/json

{
    "name": "David",
    "country": "Czech Republic"
}

# // update user
# PUT http://localhost:3001/updateUser
# content-type: application/json

# {
#     "id":1,
#     "name":"Arthur",
#     "country":"Canada"
# }


# // delete user
# DELETE http://localhost:3001/deleteUser
# content-type: application/json

# {
#     "id":1
# }
